docker:
  # URL to access the docker engine API. host.docker.internal is the default docker host ip for containers running on the same machine.
  base_url: "http://host.docker.internal:2375"
  # Name of the docker network used by the nginx container to interconnect with the other containers.
  network: proxy-network

nginx:
  # ID of the nginx container.
  container_id: nginx

  # Path to the resources of the nginx container.
  # IMPORTANT: those paths must be relative to the nginx container! Not to to the host machine!
  static_path: /config/
  private_key_path: /etc/nginx/ssl/private.key
  certificate_path: /etc/nginx/ssl/certificate.crt
  letsencrypt_path: /etc/letsencrypt/live/
  docker_config_file: dockers.conf

  # Paths the different files used by the nginx container.
  # IMPORTANT: this path is relative to the backend container! Not to to the host machine
  config_path: /app/nginx_conf/


  # Warning message for users to avoid editing the docker config file.
  config_warn_message: "#IMPORTANT IMPORTANT IMPORTANT\n# Please, do not edit this file. Use the webpage to connect your container!\n#-----------------------------------------------------------------------------------------------------"