docker:
  # Para MacOS
  # base_url: "unix:///var/run/docker.sock"  # URL estándar para el socket de Docker
  # O si estás usando Docker Desktop en MacOS, podrías necesitar:
  base_url: "unix:///Users/paula.gallucci/.docker/run/docker.sock"
  network: dev-nginx

nginx:
  container_id: deployment-iot-mqtt-2-1
  static_path: ./config/
  config_path: ./config/
  private_key_path: /etc/nginx/ssl/private.key
  certificate_path: /etc/nginx/ssl/certificate.crt
  letsencrypt_path: /etc/letsencrypt/live/
  docker_config_file: dockers.conf
  config_warn_message: "# Por favor, NO EDITES este archivo. usa dev-nginx para conectar tu contenedor!"